### ISSUE TITLE
CLI 参考如何汉化？

### ISSUE THREAD

**Issue by 522247020** [pdm-project/pdm-docs-zh#2]
命令行参考界面也是常用的查询页面，这个页面的汉化如何来做？

**Comment by 522247020** [comment]
@frostming 大哥有啥办法没！

**Comment by frostming** [comment]
>>无好办法
>>
>>或许只能解析 help 内容生成.pot 翻译文件，但这样恐怕太复杂了
>
>那目前单独做一个网页手动更新呢？

总之CLI help是通过python脚本自动生成的，你有办法映射成中文怎么都行

**Comment by 522247020** [comment]
> > > 无好办法
> > > 或许只能解析 help 内容生成.pot 翻译文件，但这样恐怕太复杂了
> > 
> > 
> > 那目前单独做一个网页手动更新呢？
> 
> 总之CLI help是通过python脚本自动生成的，你有办法映射成中文怎么都行。python脚本的自由度还是有的

我使用 Python 自带的 `gettext` 库进行操作，出现了一个问题 

```bash
- `--copier`: Use Copier to generate project [not installed] (default: `builtin`)
- `--cookiecutter`: Use Cookiecutter to generate project [not installed] (default: `builtin`)
```
在命令行显示的颜色是 红色的

![image](https://github.com/pdm-project/pdm-docs-zh/assets/38172233/eeba4c19-eb10-4fb6-a658-82302d12e865)

而在网页中出现了命令行的颜色转换符号！

![image](https://github.com/pdm-project/pdm-docs-zh/assets/38172233/3a87fc09-21c8-478b-965c-4be21009eac5)

我不清楚是不是我使用 win 的问题。

**Comment by 522247020** [comment]
在我本地测试，使用 `mkdocs serve` 预览网页情况，工作目录是 `pdm-docs-zh` 这个目录，

```python
import gettext
import argparse
import re
from pathlib import Path
from pdm.core import Core


localedir = Path("locale")
t = gettext.translation('cli', localedir=localedir, languages=['zh-CN'])
```
代码需要导入 `locale` 这个文件夹，我不确定提交代码后，执行构建文档的过程中能否找到这个文件夹
@frostming

**Comment by 522247020** [comment]
cli 汉化完成！
